Add dashboard
wulkanowy/wulkanowy pull request #1267
Opened 2021-04-02 06:41 UTC by Faierbel

2021-07-17 15:09 UTC, mklkj requested changes

2021-07-17 15:09 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
> +    }
Dlaczego puste? Jeśli jest jakiś konkretny powód to proszę o komentarz w kodzie

2021-07-18 14:25 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardFragment.kt
> +    }
bo wysyłam błędy do errorhandlera i jeśli każdy flow wywali bład to będzie mnóstwo wiadomości. Dlatego muszę sterować wysyłanie wiadomości w inny sposób

2021-07-18 14:32 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/data/repositories/ConferenceRepository.kt
> +        date: LocalDateTime = LocalDateTime.ofInstant(Instant.EPOCH, ZoneOffset.UTC)
Nie ponieważ LocalDate.MIN jest nie mieści się w zmiennej typu Long którą używamy do zapisu w bazie danych dlatego użyłem stałą Instant.EPOCH która jest po prostu zerem

2021-07-24 23:00 UTC, mklkj requested changes

2021-07-26 19:11 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/ui/modules/dashboard/DashboardAdapter.kt
> +        val sansSerifMediumFont = Typeface.create("sans-serif-medium", Typeface.NORMAL)
Bo bold jest bardziej "tłuste" od medium

2021-07-30 16:49 UTC, mklkj approved these changes

2021-07-30 16:49 UTC, merged