Migrate material date picker
wulkanowy/wulkanowy pull request #1277
Opened 2021-04-08 22:35 UTC by Luncenok

Closes #1195

2021-04-09 20:46 UTC, mklkj requested changes

2021-04-09 20:46 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/AdditionalLessonsFragment.kt
> +        constraintsBuilder.setValidator(SchoolDaysValidator())
Please add setEnd & setStart to constraints (use apply block)

2021-04-12 18:36 UTC, mklkj approved these changes

2021-04-12 19:43 UTC, Faierbel approved these changes

2021-04-12 19:43 UTC, merged