Fixes in notifications
wulkanowy/wulkanowy pull request #1292
Opened 2021-04-15 22:30 UTC by Pengwius

2021-06-12 19:13 UTC, dominik-korsa commented on app/src/main/java/io/github/wulkanowy/services/sync/works/HomeworkWork.kt
> +                .setSmallIcon(R.drawable.ic_more_homework)
Hmm?

2021-06-12 19:13 UTC, dominik-korsa commented on app/src/main/java/io/github/wulkanowy/services/sync/works/ExamWork.kt
>                  .setSmallIcon(R.drawable.ic_stat_all)
Hmmmm?

2021-06-12 19:27 UTC, Pengwius commented on app/src/main/java/io/github/wulkanowy/services/sync/works/ExamWork.kt
>                  .setSmallIcon(R.drawable.ic_stat_all)
Hmmm... I probably fucked something in resolving conflicts

2021-06-12 19:44 UTC, dominik-korsa requested changes

2021-06-12 19:44 UTC, dominik-korsa commented on app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
> +            it.filter { exam -> exam.isNotified }
Teraz sprawdziany pojawiają się w powiadomieniach przy każdej synchronizacji

2021-06-12 19:45 UTC, Pengwius commented on app/src/main/java/io/github/wulkanowy/data/repositories/ExamRepository.kt
> +            it.filter { exam -> exam.isNotified }
Wiem, zrobiłem to w celach testowych

2021-06-12 20:04 UTC, dominik-korsa requested changes

2021-06-12 20:04 UTC, dominik-korsa commented on app/src/main/res/values/strings.xml
> +        <item quantity="other">You received new %d homeworks</item>
`Homework` is uncountable

2021-06-12 20:04 UTC, dominik-korsa commented on app/src/main/res/values/strings.xml
> +        <item quantity="other">You received new %d exams</item>
```suggestion
        <item quantity="one">You received %d new exam</item>
        <item quantity="other">You received %d new exams</item>
```

2021-06-12 20:04 UTC, dominik-korsa commented on app/src/main/res/values/strings.xml
> +        <item quantity="other">You received new %d exams</item>
Also can you *receive an exam*?

2021-06-12 20:04 UTC, dominik-korsa commented on app/src/main/res/values/strings.xml
> +        <item quantity="other">You received new %d homeworks</item>
`%d` should go before `new`

2021-08-28 21:55 UTC, Faierbel approved these changes

2021-08-28 22:41 UTC, dominik-korsa approved these changes

2021-08-28 22:41 UTC, merged