Add draft message
wulkanowy/wulkanowy pull request #1306
Opened 2021-04-26 12:22 UTC by MRmlik12

2021-07-30 18:36 UTC, mklkj requested changes

2021-07-30 18:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
> +    @SuppressLint("CommitPrefEdits")
chyba już niepotrzebne

2021-07-30 18:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageDialog.kt
> +        return activity.let {
Zawartość tej metody przeniósłbym do SendActivity.showMessageBackupDialog(), a logowanie stanu do presentera

2021-07-30 18:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
> +    @FlowPreview
Zamiast tego użyj `@OptIn(FlowPreview::class)`. Po zrobieniu tego usuń `@FlowPreview` z metod wywołujących tę metodę

2021-07-30 18:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabPresenter.kt
> +    @OptIn(ExperimentalStdlibApi::class)
To jest teraz niepotrzebne

2021-07-30 18:36 UTC, mklkj commented on app/src/main/res/values/api_hosts.xml
> +        <item>http://fakelog.tk/?email</item>
Można już wrócić do .cf

2021-07-30 18:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessagePresenter.kt
> +    fun onSendMessageChange() {
Może zmienić nazwę tej metody na `onMessageContentChange()`?

2021-07-30 18:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
> +@Suppress("UNCHECKED_CAST")
Usuń tego supressa... (cd. niżej)

2021-07-30 18:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
>      @Suppress("UNCHECKED_CAST")
..., a tego przenieś... (cd. niżej)

2021-07-30 18:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/send/SendMessageActivity.kt
>      public override fun onCreate(savedInstanceState: Bundle?) {
... tutaj

2021-07-31 12:56 UTC, mklkj approved these changes

2021-07-31 16:00 UTC, Faierbel approved these changes

2021-07-31 16:00 UTC, merged