Add excuse function to "not parent" account
wulkanowy/wulkanowy pull request #1429
Opened 2021-08-05 19:10 UTC by Luncenok

Closes #1290 

Also add this function to parent account with excuse disabled by school

2021-08-20 15:33 UTC, Faierbel requested changes

2021-08-20 15:33 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
> +            val reasonFullText = context.getString(
Zamiast tworzyć stringa w presenterze i przekazywać context do presentera przekazuj dane do widoku i tam utwórz stringa

2021-08-29 13:18 UTC, Faierbel approved these changes

2021-08-29 14:52 UTC, mklkj requested changes

2021-08-29 14:52 UTC, mklkj commented on app/src/main/res/values/strings.xml
> +    <string name="attendance_excuse_formula" translatable="false">Dzień dobry,\nProszę o usprawiedliwienie mojego dziecka w dniu %s z lekcji %s%s%s.\n\nPozdrawiam.</string>
To bazowe tłumaczenie, które jest w całości po angielsku. Polskie tłumaczenie powinno być w values-pl/strings.xml

2021-08-29 14:52 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
> +            }
```suggestion
            val attendanceToExcuseNumbers = attendanceToExcuseList.map {
                it.number
            }
```

2021-08-29 14:52 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
> +                reason
Dodałbym tutaj nazwy argumentów,
![obraz](https://user-images.githubusercontent.com/12243282/131254589-96164aa0-3729-4be7-a309-53735bc46dd6.png)
polecam

2021-08-29 14:52 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
> +                attendanceToExcuseList.toList()
Add names to call arguments

2021-08-29 14:52 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendancePresenter.kt
> +            isParent = student.isParent
Ta zmienna jest używana tylko w loadData(), dlatego przeniósł bym ją na początek tej metody

2021-08-29 14:52 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/attendance/AttendanceFragment.kt
> +        context?.let { it.startActivity(SendMessageActivity.getStartIntent(it, reasonFullText)) }
Może jednak requireContext() tutaj?

2021-08-29 14:54 UTC, mklkj commented on app/src/main/res/values/strings.xml
> +    <string name="attendance_excuse_formula" translatable="false">Dzień dobry,\nProszę o usprawiedliwienie mojego dziecka w dniu %s z lekcji %s%s%s.\n\nPozdrawiam.</string>
Albo i nie, bo w sumie żyjemy w Polsce. Proszę o potwierdzenie że jednak to pomijamy

2021-08-29 17:31 UTC, mklkj approved these changes

2021-08-29 17:47 UTC, merged