Add in app review
wulkanowy/wulkanowy pull request #1435
Opened 2021-08-09 21:16 UTC by Luncenok

Closes #1142

2021-08-10 06:56 UTC, mklkj requested changes

2021-08-10 06:56 UTC, mklkj commented on app/build.gradle
> +    implementation 'com.google.android.play:core:1.10.0'
Musi być `playImplementation` - nie chcemy niewolnego kodu w buildzie dla fdroid

2021-08-12 10:38 UTC, Faierbel requested changes

2021-08-12 10:38 UTC, Faierbel commented on app/src/main/res/values/preferences_defaults.xml
> +    <string name="pref_default_in_app_review">0</string>
Te ustawienia się są wyświetlane użytkonikowi więc nie muszą byc jako string resource. Wystarczy że je dasz w klasie

2021-08-12 10:38 UTC, Faierbel commented on app/src/main/res/values/preferences_keys.xml
> +    <string name="pref_key_in_app_review">in_app_review</string>
Klucze do ustawień nie wyświetlanych użytkonikowi przetrzymuj w klasie jako stałe tak jak podobnie zrobiłem z dashboard postions

2021-08-12 10:38 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
> +                prefRepository.inAppReviewCount++
Wydziel ten kod do oddzielnej funkcji

2021-08-12 10:43 UTC, Faierbel requested changes

2021-08-12 10:43 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
> +    var inAppReviewDate: LocalDate
Przetrzymuja datę jako long a nie string i może byłoby lepiej zrobić z tego nullable i sprawdzać nulla a nie czy rok to rok 1970

2021-08-28 22:22 UTC, Faierbel approved these changes

2021-08-28 22:30 UTC, mklkj approved these changes

2021-08-28 22:43 UTC, merged