Add timetable change notification
wulkanowy/wulkanowy pull request #1547
Opened 2021-09-29 17:14 UTC by Luncenok

2021-11-01 21:02 UTC, mklkj requested changes
to be continued...

2021-11-03 16:43 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/ui/modules/settings/SettingsFragment.kt
> +    override fun showChangePasswordSnackbar(redirectUrl: String) {}
Nie ma żadnej różnicy a że SettingsFragment jest klasą implementującą interfejs to może to tu pasuje

2021-11-05 20:58 UTC, mklkj requested changes

2021-11-05 20:58 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/Destination.kt
> +    val fragment: Fragment
to chyba powinno być na samej górze, przed enumem

2021-11-05 20:58 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/main/MainPresenter.kt
> +    private val rootDestinationType = listOf(
rootDestinationTypeList lub rootDestinationTypes

2021-11-05 20:58 UTC, mklkj commented on app/src/main/res/values/strings.xml
> +    <string name="timetable_notify_change_subject">\nChange of Subject from %s to %s</string>
Stringi zaczynające się od nowej linii to trochę dziwna rzecz. W istniejącym już StringBuilderze lepiej jest wywołać appendLine()

2021-11-06 21:20 UTC, mklkj approved these changes

2021-11-06 21:21 UTC, merged