Add additional lessons feature
wulkanowy/wulkanowy pull request #1550
Opened 2021-10-01 04:28 UTC by Luncenok

2021-10-01 09:21 UTC, mklkj requested changes

2021-10-01 09:21 UTC, mklkj commented on app/schemas/io.github.wulkanowy.data.db.AppDatabase/40.json
> +    "identityHash": "a2784e3a8e3a858132d1dbbc71b0a0d2",
Please NEVER edit schema files

2021-12-12 23:24 UTC, mklkj requested changes

2021-12-12 23:24 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddDialog.kt
> +            .setMinute(end?.minute ?: 15)
Ustawmy tu bardziej przydatne wartości domyślne - niech dla początkowej godziny będzie to powiedzmy 15:00, a dla tej (czyli końcowej) - 15:45

2021-12-12 23:24 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddDialog.kt
> +    override fun showStartTimePickerDialog() {
Ta metoda jest prawie identyczna jak ta niżej - możemy pomyśleć nad wydzieleniem kolejnej metody z takimi parametrami jakie te metody różnią

2021-12-12 23:24 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddDialog.kt
> +    private var end: LocalTime? = null
To jest stan - powinien znaleźć się w prezenterze

2021-12-12 23:24 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddPresenter.kt
> +        if (!isError) {
Wydzieliłbym ten fragment do metody typu isUserInputValid()

2021-12-12 23:24 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddPresenter.kt
> +            val semester = semesterRepository.getCurrentSemester(student)
Operacje na bazie danych bez error handlera - grozi crashem apki

2021-12-12 23:24 UTC, mklkj commented on app/src/main/res/layout/dialog_additional_add.xml
> +                android:inputType="none"
Czemu none? Ustawmy na `text` tak, żeby nie dało się wpisać znaku nowej linii

2021-12-17 19:34 UTC, mklkj requested changes
dodatkowo nadal mogę ustawić Start time będący później niż End time. To nie powinno przejść (bo jest bez sensu)

2021-12-17 19:34 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddPresenter.kt
> +                .getOrNull() ?: return@launch
nie lepiej jeden runCatching (jak już tego użyłeś)? nie widzę sensu w takim dzieleniu tego

2021-12-17 19:34 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddDialog.kt
> +    private fun showTimePickerDialog(defaultTime: LocalTime, onTimeSelected: (LocalTime) -> Unit) {
zmieńmy może defaultTime na selectedTime (to samo przy metodach wywołujących tę)

2021-12-17 19:36 UTC, mklkj requested changes

2021-12-17 19:36 UTC, mklkj commented on app/src/main/res/layout/dialog_additional_add.xml
> +                android:maxLines="4" />
czemu 4 linie? To jest nazwa przedmiotu! Jedna linia to max

2021-12-20 00:48 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddPresenter.kt
> +                .getOrNull() ?: return@launch
No ale potrzebuję semester i studenta do późniejszego kodu więć potrzebuję dwa runCatching. Jak ma to wyglądać w jednym

2021-12-20 01:05 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddPresenter.kt
> +                .getOrNull() ?: return@launch
I jak ma ograniczyć end time? Po prstu wyświetlić error text po inputem?

2021-12-20 21:43 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/additional/add/AdditionalLessonAddPresenter.kt
> +                .getOrNull() ?: return@launch
Nie potrzebujesz studenta później - każdy semestr ma już studentId, którego możesz bezpiecznie użyć

2021-12-20 23:35 UTC, mklkj approved these changes

2021-12-20 23:37 UTC, merged