Add attendance calculator
wulkanowy/wulkanowy pull request #1597
Opened 2021-10-22 00:40 UTC by mibac138

| ![image](https://user-images.githubusercontent.com/5672750/138375281-f333e2b4-16ff-4381-b24e-97cf72078308.png) | ![image](https://user-images.githubusercontent.com/5672750/138375371-038f22b7-e337-48e7-bc93-cf122d4818d6.png) | ![image](https://user-images.githubusercontent.com/5672750/138375329-dea7bb48-5b4b-4b04-9fd1-6f7949b10ff1.png) | ![image](https://user-images.githubusercontent.com/5672750/138375355-553a54b4-dda6-4965-a4d8-f9e4b2650138.png) |
|---|---|---|---|

2022-11-19 13:14 UTC, mklkj commented
@mibac138 zrobisz rebase/merge w wolnej chwili?

2022-11-22 20:56 UTC, mklkj requested changes

2022-11-22 20:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/db/dao/AttendanceSummaryDao.kt
> +import io.github.wulkanowy.data.db.entities.AttendanceSummaryWithName
remove this import

2022-11-22 20:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/db/entities/AttendanceSummaryWithName.kt
> +package io.github.wulkanowy.data.db.entities
remove this file

2022-11-22 20:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/repositories/PreferencesRepository.kt
> +    val targetAttendance: Flow<Int>
add "flow" suffix (every other flow-property has it)

2022-11-22 20:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/domain/attendance/GetAttendanceCalculatorDataUseCase.kt
> +data class AttendanceData(
move this data class to data.pojos

2022-11-22 20:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/domain/attendance/GetAttendanceCalculatorDataUseCase.kt
> +        else (allPresences.toDouble() / total) * 100
avoid domain-logic in data structure, move those to constructor properties

2022-11-22 20:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/domain/attendance/GetAttendanceCalculatorDataUseCase.kt
> +                    summaries.sumOf { it.allAbsences })
add names to constructor parameters

2022-11-22 20:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/domain/attendance/GetAttendanceCalculatorDataUseCase.kt
> +                student, semester, subject.realId, forceRefresh
add names to constructor parameters

2022-11-22 20:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/attendance/calculator/AttendanceCalculatorAdapter.kt
> +            if (presences / (item.total + 1f) >= targetFreq) {
soo maybe move this logic to use case?

2022-11-23 12:51 UTC, mklkj requested changes

2022-11-23 12:51 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/attendance/calculator/AttendanceCalculatorAdapter.kt
> +    var targetFreq: Double = 0.5
it looks like this is no longer needed

2022-11-23 12:51 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/attendance/calculator/AttendanceCalculatorAdapter.kt
> +    override fun getItemCount() = items.size
move this above onCreateViewHolder() (we always preserve this order in adapters)

2024-03-08 19:31 UTC, Faierbel approved these changes

2024-03-08 19:35 UTC, mklkj approved these changes

2024-03-08 19:36 UTC, merged