Add mini-proxy support for DEV
wulkanowy/wulkanowy pull request #1624
Opened 2021-11-01 18:37 UTC by Zaptyp

Adding proxy support only for DEV versions

2021-11-03 16:40 UTC, Faierbel requested changes

2021-11-03 16:40 UTC, Faierbel commented on app/src/main/res/xml/network_security_config.xml
> +      <!--Trust user added CAs while debuggable only -->
Usuń komentarz bo jest zbędny.

2021-11-03 16:40 UTC, Faierbel commented on app/src/main/res/xml/network_security_config.xml
> +<base-config cleartextTrafficPermitted="true"/>
Możesz usnąć cleartextTrafficPermitted="true"

2021-11-03 17:44 UTC, Zaptyp commented on app/src/main/res/xml/network_security_config.xml
> +<base-config cleartextTrafficPermitted="true"/>
Jak usunę to aplikacja nie będzie się mogła połączyć z fakelogiem

2021-11-03 17:44 UTC, Zaptyp commented on app/src/main/res/xml/network_security_config.xml
> +      <!--Trust user added CAs while debuggable only -->
Ok

2021-11-04 02:07 UTC, Faierbel approved these changes

2021-11-04 02:09 UTC, merged