Migrate to material3
wulkanowy/wulkanowy pull request #1660
Opened 2021-11-20 01:53 UTC by Daxxxis

2023-03-11 20:58 UTC, mklkj requested changes

2023-03-11 20:58 UTC, mklkj commented on app/src/main/res/values-v31/colors.xml
> +    <color name="colorCards">@color/material_dynamic_secondary95</color>
to jest gdzieś używane?

2023-03-11 20:58 UTC, mklkj commented on app/src/main/res/values-night-v31/colors.xml
> +    <color name="colorCardsDark">@color/material_dynamic_secondary20</color>
i to (ja nie znalazłem)

2023-03-11 20:58 UTC, mklkj commented on app/src/main/res/xml/provider_widget_timetable.xml
> +    android:previewLayout="@layout/widget_timetable_preview"
tu by się jakiś suppress się przydał, bo to tylko dla api >=31, tak samo te dwa atrybuty niżej

2023-03-11 20:58 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsDialog.kt
> +    private var dialogView: View? = null
a może by zrobić coś takiego? https://hastebin.cf/ojohejezaw.diff

2023-03-17 23:58 UTC, Faierbel commented on app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsAdapter.kt
> +                backgroundTintList = ColorStateList.valueOf(ContextCompat.getColor(context, grade.getBackgroundColor(gradeColorTheme)))
Po co robić utlis dla jednego przypadku

2023-03-18 00:03 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsAdapter.kt
> +                backgroundTintList = ColorStateList.valueOf(ContextCompat.getColor(context, grade.getBackgroundColor(gradeColorTheme)))
to nie jest tylko jeden przypadek https://hastebin.cf/gayuqeqaca

2023-03-29 20:14 UTC, mklkj approved these changes

2023-03-29 20:14 UTC, merged