Refactor notification destinations
wulkanowy/wulkanowy pull request #1709
Opened 2021-12-08 00:58 UTC by mibac138

Timetable notifications in notifications center open the correct day

2021-12-08 01:00 UTC, mibac138 commented on app/src/main/java/io/github/wulkanowy/ui/modules/Destination.kt
> +    data class Timetable(private val date: Long? = null) : Destination() {
Alternatively, can be replaced with `@Serializable data class Timetable(@Serializable(with = LocalDateSerializer::class) val date: LocalDate? = null) : Destination() { ... }`

2021-12-30 06:08 UTC, mibac138 commented on app/src/main/java/io/github/wulkanowy/data/db/entities/Notification.kt
> +    @ColumnInfo(defaultValue = "")
This will not work. The notification center will load forever if any entity has this (`""`) value (error: `Loading notifications result: An exception occurred: kotlinx.serialization.json.internal.JsonDecodingException: Cannot begin reading element, unexpected token: 10
    JSON input: `). The default value must be a valid one. The previous value was: `Converters().destinationToString(Destination.Dashboard)` (equivalent to  `{"type":"io.github.wulkanowy.ui.modules.Destination.Dashboard"}`)

2022-01-23 18:56 UTC, mklkj requested changes

2022-01-23 18:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/db/migrations/Migration48.kt
> +        val defaultDestination = Converters().destinationToString(Destination.Dashboard)
Nie jestem pewny, czy to na pewno dobry pomysł - jeśli zmieni się w przyszłości zachowanie tego konwertera, a dodana zostanie migracja polegająca na wyjściu z niego, to będziemy mieli trudny do namierzenia błąd.

Może lepiej będzie na sztywno wpisać tutaj `{"type":"io.github.wulkanowy.ui.modules.Destination.Dashboard"}`. Bo to jest wartością zwracaną przez ten konwerter

2022-01-23 18:56 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/services/sync/notifications/ChangeTimetableNotification.kt
> +                else -> Destination.Timetable()
Nie lepiej zamiast tego posortować zmiany od najbliższego dnia i do tego właśnie dnia przenosić ZAWSZE?

2022-01-27 11:48 UTC, mklkj approved these changes

2022-01-28 11:39 UTC, mklkj approved these changes

2022-01-28 12:43 UTC, merged