Fix notification spam after login
wulkanowy/wulkanowy pull request #1715
Opened 2021-12-10 05:41 UTC by mibac138

Fixes #1610

2021-12-28 14:11 UTC, mklkj requested changes

2021-12-28 14:11 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/services/sync/SyncWorker.kt
>                  work.doWork(student, semester)
zamiast kombinować z `isNotificationsEnable` myślę, że dużo lepszym pomysłem będzie przekazanie tutaj tej flagi do każdego z workerów tak, żeby dało się z tego miejsca sterować wysyłaniem powiadomień, coś a'la `doWork(student, semester, enableNotifications = !quiet && preferencesRepository.isNotificationsEnable)`

2021-12-28 14:42 UTC, mklkj approved these changes

2021-12-29 07:31 UTC, Faierbel approved these changes

2021-12-29 07:31 UTC, merged