Mute messages
wulkanowy/wulkanowy pull request #2415
Opened 2024-02-07 14:15 UTC by JestemKamil

Nie testowałem systemu mutów na wielu użytkownikach, więc prawdopodobnie TODO: dodać studentID do tabeli z mutami

2024-02-08 16:57 UTC, mklkj requested changes

2024-02-08 16:57 UTC, mklkj commented on app/src/main/res/values-pl/strings.xml
> +    <string name="message_unmute">Wyłącz wyciszenie</string>
lepiej nie dodawaj tego tutaj - używamy crowdina do tłumaczeń i jak wrzucisz tu tłumaczenia to trzeba potem będzie konflikty rozwiązywać

2024-02-08 16:57 UTC, mklkj commented on app/src/main/res/menu/action_menu_message_preview.xml
> +        android:icon="@drawable/ic_menu_message_delete"
tej ikony niby nie widać, ale jak ktoś będzie miał szerszy ekran, to zobaczy ikonkę usuwania. Może dajmy tutaj tę samą, która jest pokazywana na liście wiadomości?

2024-02-08 16:57 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/tab/MessageTabAdapter.kt
> +            when(message.isMuted) {
nie zapomnij refromatować kodu, masz od tego skrót klawiszowy https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat_file

2024-02-08 16:57 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewView.kt
> +    fun updateMuteButton(muted: Boolean)
```suggestion
    fun updateMuteToggleButton(isMuted: Boolean)
```

2024-02-08 16:57 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/db/entities/Message.kt
> +    var isMuted: Boolean = false
Czy to na pewno tu jest potrzebne? Wydaje się być niepotrzebnym _brudzeniem_ tabeli z wiadomościami. Spróbuj tę flagę przemycić przez złączenie z nową tabelą w taki sposób jak zostało to zrobione w encji `MessageWithAttachment` tak, żeby do każdej wiadomości był od razu przydzielony obiekt z powiązanym wyciszonym odbiorcą

2024-02-08 16:57 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
> +    private val studentRepository: StudentRepository,
Lepiej tak nie róbmy (tj. nie wstrzykujmy repo do repo), bo łatwo w końcu doprowadzić do sytuacji, gdzie będziemy próbowali wstrzyknąć np. student repo do message repo, a potem message repo do student repo (i to drugie już z oczywistych względów się nie uda).
Zamiast tego proponuję zrobić tak, jak jest to robione we wszystkich innych miejscach, tj. w presenterze wywołać getCurrentUser() i przekazać tak zdobyty ID usera do metody w tym repozytorium

2024-02-08 16:57 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
> +            }
koniecznie otocz ten kod w runCatching {} (tak jak w innych miejscach, np. patrz BasePresenter.onConfirmDecryptionFailedSelected) żeby uniknąć ewentualnego crasha w przypadku wystąpienia wyjątku

2024-02-08 16:57 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
> +        message ?: return false
możesz zrobić taki myk w stylu `val message = message ?: return false`, wtedy niżej będziesz mieć dostęp do `message` bez tego nulla i będziesz mógł usunąć te wszystkie `!!`

2024-02-10 11:28 UTC, mklkj requested changes

2024-02-10 11:28 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/db/AppDatabase.kt
> +    abstract val mutesDao: MutedMessageSendersDao
zaktualizuj tę nazwę zmiennej

2024-02-10 11:28 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
> +    private val mutesDb: MutedMessageSendersDao,
zaktualizuj tę nazwę

2024-02-10 11:28 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
> +                }
czy na sto procent tak chcemy? Np. wiadomości na takim Messengerze, jeśli wyciszymy czat nadal będą oznaczane jako nieodczytane, co ma sens, bo faktycznie ich nie odczytaliśmy

2024-02-10 11:28 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/message/preview/MessagePreviewPresenter.kt
> +        }.logResourceStatus("message ${messageToLoad.messageId} preview").onResourceData {
przywróćmy oryginalne formatowanie, tj. logResourceStatus oraz onResourceData przenieśmy do nowych linii, czyli tak jak było

2024-02-10 14:29 UTC, JestemKamil commented on app/src/main/java/io/github/wulkanowy/data/repositories/MessageRepository.kt
> +                }
nie chcemy nawet na 1% - zmieniono

2024-02-10 14:44 UTC, mklkj approved these changes

2024-02-29 20:30 UTC, merged