Notify widgets about data updates
wulkanowy/wulkanowy pull request #2487
Opened 2024-03-14 16:29 UTC by mibac138

Fixes #2350

2024-03-14 17:04 UTC, mklkj requested changes

2024-03-14 17:04 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/utils/WidgetUtils.kt
> +fun Context.updateAllWidgets(widgetProvider: KClass<out BroadcastReceiver>) {
zrób z tego normalną klasę i ją wstrzykuj przez konstruktor, bo teraz to repo stało się nietestowalne

2024-03-15 09:44 UTC, Faierbel approved these changes

2024-03-17 20:05 UTC, mklkj approved these changes

2024-03-17 20:06 UTC, merged