Hide grade statistics when is eduOne
wulkanowy/wulkanowy pull request #2496
Opened 2024-03-21 08:23 UTC by Faierbel

2024-03-21 21:12 UTC, mklkj requested changes

2024-03-21 21:12 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/WulkanowySdkFactory.kt
> +        if (student.isEduOne) return true
To sprawdzenie jest niewystarczające, a nawet błędne, bo jak ktoś nie ma eduOne to apka będzie przy każdym wywołaniu tej metody pobierała ucznia, więc np. przy synchronizacji zamiast `n` requestów wykonamy ich co najmniej `2n`

2024-03-22 08:57 UTC, mklkj requested changes

2024-03-22 08:57 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/WulkanowySdkFactory.kt
> +        eduOneMutex.withLock {
tu będzie problem ze współbieżnością, potrzebne coś w rodzaju double locka https://pl.wikipedia.org/wiki/Blokada_z_podw%C3%B3jnym_zatwierdzeniem

2024-03-23 15:36 UTC, mklkj requested changes

2024-03-23 15:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
> +        ).getCurrentOrLast()
mamy non-fatale odnośnie errora o braku semestrów. Trzeba to jakoś obsłużyć. Dodaj też w tej metodzie jakieś logi, żeby było trochę więcej kontekstu w crashlytics odnośnie tego, co się tutaj właściwie dzieje i na czym się zakończyło

2024-03-23 15:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
> +        val studentIsAuthorizedAndEduOne = StudentIsAuthorized(
nazwa zmiennej chyba już nieaktualna

2024-03-23 15:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/WulkanowySdkFactory.kt
> +    private suspend fun migrateStudentToEduOneIfNecessary(student: Student): Boolean {
Nie podoba mi się deklaracja tej metody. Niby jest tryb rozkazujący i `migrate`, ale zwraca jakiegoś booleana. Tak się zwykle robi do zwrócenia tego, czy operacja się powiodła czy nie, ale parę linijek niżej wychodzi, że true jest tylko wtedy, gdy uczeń używa eduOne. Trochę to mylące. 

Może jakoś zmieńmy typ zwracany na Unit a odpytywanie bazy danych przenieśmy do metody wywołującej `migrateStudentToEduOneIfNecessary()`?

2024-03-23 15:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/WulkanowySdkFactory.kt
> +            ).getCurrentOrLast()
Tak jak w sprawdzaniu stanu autoryzacji - może powodować dodatkowe "crashe". Przypomnij mi jak nie dam ci znać, ale muszę sprawdzić, czy na pewno jest tutaj ten semestr potrzebny w ogóle, bo logiczne by było, gdyby nie był

2024-03-23 15:36 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/db/entities/Student.kt
> +    val isEduOne: Boolean?,
Ta zmiana bez dodatkowej logiki sprawi, że wszyscy użytkownicy z wersji 2.5.2 będą mieli tutaj wartość non-null, przez co migracja z WulkanowySdkFactory nie uruchomi się dla nic wcale. Potrzeba dodatkowego kodu resetującego ten stan na null, ale moim zdaniem już tylko dla tych, którzy mają `isEduOne` ustawione na `false`, bo ci co mają `true` to dla nich migracja nic nie zmieni

2024-03-23 15:36 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +        runBlocking {
zamiast tego użyj runTest {} dla całego bloku z testem

2024-03-23 15:36 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +@RunWith(RobolectricTestRunner::class)
do czego potrzebujemy tutaj robolectric?

2024-03-23 15:36 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +    private lateinit var sdk: Sdk
czemu nie użyjesz adnotacji @MockK?

2024-03-23 15:36 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +        verify { sdk.isEduOne = true }
dodaj jeszcze verify dla wywołania metod pobierających currentStudent z sdk

2024-03-23 15:36 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +        verify { sdk.isEduOne = true }
dodaj verify sprawdzające, że getCurrentStudent nie zostało wywołane

2024-03-23 15:36 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +        verify { sdk.isEduOne = false }
dodaj verify sprawdzające, że getCurrentStudent zostało wywołane

2024-03-23 15:36 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +        verify { sdk.isEduOne = false }
tu też dodaj te sprawdzenia

2024-03-23 15:36 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +class WulkanowySdkFactoryTest {
dodaj jeszcze test sprawdzający co się stanie w przypadku wystąpienia wyjątku w getCurrentStudent() i/lub innej metodzie, przez którą migracja zachowałaby się inaczej

2024-03-23 16:56 UTC, Faierbel commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +    private lateinit var sdk: Sdk
A co to za różnica? nie uzywająć annotacji jest mniej linijek kodu

2024-03-23 17:00 UTC, Faierbel commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +        verify { sdk.isEduOne = true }
sdk jest mockiem i by wywaliło i tak błąd że MockK nie ma odpowiedzi dla getCurrentStudent ale dodam verify

2024-03-23 17:14 UTC, Faierbel commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +@RunWith(RobolectricTestRunner::class)
Aby nie nie robić wstrzykiwania dla tych android.os.Build https://github.com/wulkanowy/wulkanowy/blob/bugfix/2.5.3/app/src/main/java/io/github/wulkanowy/data/WulkanowySdkFactory.kt#L21

2024-03-24 03:39 UTC, mklkj requested changes

2024-03-24 03:39 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/repositories/StudentRepository.kt
> +        ).getCurrentOrLast()
Usunąłem z sdk wymóg ustawionego semestru, sprawdź ponownie na eduOne i nie-eduOne czy będzie git

2024-03-24 03:39 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +@RunWith(RobolectricTestRunner::class)
Ma sens. Choć, ciekawostka, w skrajnych przypadkach dałoby się zmockować przez MockK statyczne pola https://stackoverflow.com/a/49819729/6695449

2024-03-24 03:39 UTC, mklkj commented on app/src/test/java/io/github/wulkanowy/data/WulkanowySdkFactoryTest.kt
> +    private lateinit var sdk: Sdk
Niby niewielka, ale byłoby spójnie ze wszystkimi innymi testami

2024-03-24 03:39 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/data/WulkanowySdkFactory.kt
> +            ).getCurrentOrLast()
Poprawione w sdk - semestr nie powinien być już wymagany ani dla eduOne ani dla nie-eduOne

2024-03-24 18:35 UTC, mklkj approved these changes

2024-03-24 18:42 UTC, merged