Add subjects sorting in "Grades"
wulkanowy/wulkanowy pull request #946
Opened 2020-09-03 18:37 UTC by PanTajemnic

Closes #818

2020-09-06 12:08 UTC, mklkj requested changes

2020-09-06 12:08 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
> +            .let {
Ustal tutaj nazwę zmiennej zamiast `it` (na np. `grades`), bo poniżej jest clash nazw zmiennych

2020-09-06 12:08 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
> +                    it.sortedByDescending { it.grades.first().date }
Będzie mały problem z `grades.first()` gdy zmergujemy #947 - first() będzie zwracało czasem `NoSuchElementException`

2020-09-06 12:08 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
> +                else it.sortedBy { it.subject.toLowerCase() }
Zsuppressuj warning który się tutaj pojawia przez dodanie `@SuppressLint("DefaultLocale")` nad metodą

2020-09-06 12:08 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/grade/details/GradeDetailsPresenter.kt
> +                if (preferencesRepository.gradeSortingMode == "date")
Lepiej do takiego porównywania stworzyć enuma, coś jak `GradeAverageMode`

2020-09-25 13:43 UTC, Faierbel approved these changes

2020-09-27 14:16 UTC, mklkj approved these changes

2020-09-27 14:28 UTC, merged