Show groups next to subjects in timetable
wulkanowy/wulkanowy pull request #953
Opened 2020-09-08 16:56 UTC by PanTajemnic

Closes #942

2020-09-08 20:21 UTC, mklkj requested changes

2020-09-08 20:21 UTC, mklkj commented on app/src/main/java/io/github/wulkanowy/ui/modules/timetable/TimetableAdapter.kt
> +            if (showGroupsInPlan) timetableItemGroup.text = lesson.group
Brakuje czyszczenia tego pola w `else` co może powodować błędy w wyświetlaniu tej informacji przy długich listach. `onBindViewHolder` w recycler view działa tak, że widok który został już wcześniej utworzony zostaje użyty ponownie i są do niego podstawiane nowe dane właśnie w tej metodzie. Jeśli nie ustawisz wszystkich pól przy każdym bindzie, wartości ustawione dla poprzednio utworzonego widoku w nim zostaną

2020-09-25 13:40 UTC, Faierbel approved these changes

2020-09-25 13:41 UTC, Faierbel approved these changes

2020-09-27 14:15 UTC, mklkj approved these changes

2020-09-27 14:33 UTC, merged